### ISSUE TITLE
Update ressources link in README

### ISSUE THREAD

**Issue by makayabou** [synalp/jtrans#40]
Hello,
Ressources link in README is not working, however link indicated in last commit is good.
Could you please update link in README?
thanks

**Comment by sbibauw** [comment]
Hi! Thanks @makayabou for pointing at the link in the last commit (resources: http://synalp.loria.fr/jtrans/jtrans_res_20140416.zip).

I'd like to add that various other links are dead and the corresponding files have not been made available on http://synalp.loria.fr/jtrans/ : 

- Prebuilt executable: `jtrans.jar`
- ASR resources: `jtrans_asr_20140416.zip`
- Sample of the TCOF corpus: `ag_ael.zip`

Any possibility to upload those as well to the Synalp domain?

**Comment by cerisara** [comment]
Hello,

Sorry for the long silence (I'm not notified of issues); I've just updated the README and links.
They should be up and running again for several years...

Thanks for the issue !
