### ISSUE TITLE
Resource missing for ASR mode

### ISSUE THREAD

**Issue by cveaux** [synalp/jtrans#42]
Hi, I'd like to test JTrans in ASR mode, however I got this error:

`java.io.FileNotFoundException: https://synalp.loria.fr/jtrans/jtrans_asr_20140416.zip`

It would seem that the link to jtrans_asr_20140416.zip is broken.

Is it possible to download this file manually from another location?

Thanks.

**Comment by cerisara** [comment]
The README.md now provides a working link (as of July 20th, 2022) to manually download the resources.
